// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview This file contains the Genkit flow for enhancing the skills section of a resume using AI.
 *
 * - enhanceResumeSkills - A function that enhances the skills section of a resume.
 * - EnhanceResumeSkillsInput - The input type for the enhanceResumeSkills function.
 * - EnhanceResumeSkillsOutput - The return type for the enhanceResumeSkills function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const EnhanceResumeSkillsInputSchema = z.object({
  skillsSection: z
    .string()
    .describe('The skills section of the resume that needs enhancement.'),
  jobDescription: z
    .string()
    .optional()
    .describe('The job description for which the resume is being tailored.'),
});
export type EnhanceResumeSkillsInput = z.infer<typeof EnhanceResumeSkillsInputSchema>;

const EnhanceResumeSkillsOutputSchema = z.object({
  enhancedSkillsSection: z
    .string()
    .describe('The enhanced skills section of the resume.'),
});

export type EnhanceResumeSkillsOutput = z.infer<typeof EnhanceResumeSkillsOutputSchema>;

export async function enhanceResumeSkills(input: EnhanceResumeSkillsInput): Promise<EnhanceResumeSkillsOutput> {
  return enhanceResumeSkillsFlow(input);
}

const enhanceResumeSkillsPrompt = ai.definePrompt({
  name: 'enhanceResumeSkillsPrompt',
  input: {schema: EnhanceResumeSkillsInputSchema},
  output: {schema: EnhanceResumeSkillsOutputSchema},
  prompt: `You are a resume expert specializing in optimizing the skills section to highlight a candidate's abilities and expertise.

  You will receive the current skills section of a resume and a job description (if provided).
  Your goal is to enhance the skills section to make it more impactful and tailored to the job description, if provided.

  Skills Section:
  {{skillsSection}}

  Job Description (Optional):
  {{jobDescription}}

  Enhanced Skills Section:`,
});

const enhanceResumeSkillsFlow = ai.defineFlow(
  {
    name: 'enhanceResumeSkillsFlow',
    inputSchema: EnhanceResumeSkillsInputSchema,
    outputSchema: EnhanceResumeSkillsOutputSchema,
  },
  async input => {
    const {output} = await enhanceResumeSkillsPrompt(input);
    return output!;
  }
);
